OPENAI_API_KEY = "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"

[connections.snowflake]
user = "DANDEDIME"
password = "FucktheG0P!"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "bwazaom-gl06291"
